---
- name: Deploy chrony configuration
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start chrony
  systemd:
    name: chrony
    state: restarted
    enabled: yes
